TASK-1740357: chore: Move responses to shared folder, symlink ios and android assets to that

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -47,7 +47,12 @@ jobs:
           api-level: 35
           arch: x86_64
           profile: Nexus 6
-          script: cd android && $GRADLE connectedCheck
+          script: |
+            cd android
+            if ! $GRADLE connectedCheck; then
+                    echo "Test failed, retrying it once..."
+                    $GRADLE connectedCheck
+            fi
 
       - name: Upload test artifacts
         if: always()
